export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/zfs/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"

export TERM="xterm-256color"

# ==== Mise ====
eval "$(mise activate zsh)"

# ==== zinit ====
source /opt/homebrew/opt/zinit/zinit.zsh
zinit ice depth=1
zinit light romkatv/powerlevel10k
zinit light zsh-users/zsh-autosuggestions # suggestions and tab-completion for commands
zinit light zsh-users/zsh-syntax-highlighting
zinit light MichaelAquilina/zsh-auto-notify # notifications for long-running commands
zinit ice wait"1" lucid from"gh-r" as"program" mv"jq-* -> jq" pick"jq"
zinit wait"1" pack"default+keys" for fzf # fuzzy find for CTRL-R history

# ==== Powerlevel10k ====
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs command_execution_time status background_jobs_joined)
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='black'
POWERLEVEL9K_STATUS_CROSS=true

# ==== zsh customization ====
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
HISTFILE=~/.zsh_history
setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
